### ISSUE TITLE
Customizing moonwm-menu

### ISSUE THREAD

**Issue by garaiza-93** [jzbor/MoonWM#1]
I'm lost on how to customize moonwm-menu. I have most other things colored how I like it, but not this pop-up menu. I'm happy to tinker with files, but if I can get away with some environment variables, that's even better.

**Comment by jzbor** [comment]
Hi, the way it worked until 7.1.1 was really sketchy. In order to avoid having an extra dependency I hacked my way around it by having a script that imports env variables from a file before starting the wm. That sucks. So now I am changing it to load a file `~/.config/moonwm/config.xres` in the same format that `~/.Xresources` uses. I still need a couple of days to finish it up, as live reloading of the colors (`mod + F5`) still isn't working as well as before.

Sorry for my late response - I was on holiday. Thanks for trying it out! My "development cycle" (or however you want to call it) was pretty rough until now, because only me and my friends was using it, so I could hit them up in person if somethings up. In the next few weeks I will release 7.2 which will fix some bugs and introduce the new config system. From then on there are no further changes planned yet, but who know. I will however make sure to improve the development process and documentation, so it's such a mess.

**Comment by jzbor** [comment]
So I think I fixed it all. I also updated the documentation. If I find nothing problematic I'll release the new version next week.

**Comment by jzbor** [comment]
I have improved the documentation on customizing xmenu in the last release - closing this issue now.
