### ISSUE TITLE
Is it possible to implement the directional navigation in dwm?

### ISSUE THREAD

**Issue by etherbiswas** [jzbor/MoonWM#3]
How are you doing the directional navigation i.e;
<pre>M-J: focus Down
M-k: focus Up
M-l: focus right
M-h: focus left</pre>
and Shift to swap clients?

**Comment by etherbiswas** [comment]
https://github.com/jzbor/patches

**Comment by etherbiswas** [comment]
i found this repo with the patch. But last commit was 2 years ago? is this the one used in moonwm and will it be update in the future?

**Comment by jzbor** [comment]
Hi, the main function in moonwm handling this is [`nextdir`](https://github.com/jzbor/moonwm/blob/10e4dbb03d90e7bd637d1aafbfb233c699f09465/src/moonwm.c#L2313). It is in turn used by [`focusdir`](https://github.com/jzbor/moonwm/blob/10e4dbb03d90e7bd637d1aafbfb233c699f09465/src/moonwm.c#L1505) for switching the focused window and [`movedir`](https://github.com/jzbor/moonwm/blob/10e4dbb03d90e7bd637d1aafbfb233c699f09465/src/moonwm.c#L2051) for moving/swapping windows. It's been some time since I wrote this code and honestly there is a lot of room for improvement. It does not work fine with all layouts especially with stuff like [cfacts](https://dwm.suckless.org/patches/cfacts/). 

I am pretty sure I started of with [this](https://github.com/bakkeby/patches/blob/master/dwm/dwm-focusdir-6.2.diff) patch from bakkeby. Maybe that helps you a little. My fork was only for some pull requests on some other patches.

Reworking this has been on my todo list for a long time now, but I simply haven't had a good idea that works well with all layouts including floating. If you wish to try my version you _should_ be fine with adding the functions mentioned above (`focusdir`, `movedir` and `nextdir`), but there is no guarantee, since MoonWM has had a lot of changes since dwm and the directional functions are pretty much tailored towards it's standard layouts.

**Comment by etherbiswas** [comment]
> 


> Hi, the main function in moonwm handling this is [`nextdir`](https://github.com/jzbor/moonwm/blob/10e4dbb03d90e7bd637d1aafbfb233c699f09465/src/moonwm.c#L2313). It is in turn used by [`focusdir`](https://github.com/jzbor/moonwm/blob/10e4dbb03d90e7bd637d1aafbfb233c699f09465/src/moonwm.c#L1505) for switching the focused window and [`movedir`](https://github.com/jzbor/moonwm/blob/10e4dbb03d90e7bd637d1aafbfb233c699f09465/src/moonwm.c#L2051) for moving/swapping windows. It's been some time since I wrote this code and honestly there is a lot of room for improvement. It does not work fine with all layouts especially with stuff like [cfacts](https://dwm.suckless.org/patches/cfacts/).
> 
> I am pretty sure I started of with [this](https://github.com/bakkeby/patches/blob/master/dwm/dwm-focusdir-6.2.diff) patch from bakkeby. Maybe that helps you a little. My fork was only for some pull requests on some other patches.
> 
> Reworking this has been on my todo list for a long time now, but I simply haven't had a good idea that works well with all layouts including floating. If you wish to try my version you _should_ be fine with adding the functions mentioned above (`focusdir`, `movedir` and `nextdir`), but there is no guarantee, since MoonWM has had a lot of changes since dwm and the directional functions are pretty much tailored towards it's standard layouts.

Thanks a lot!

**Comment by etherbiswas** [comment]
I actually had this fork i did a while back: https://github.com/Ahanaf-Ether/dwm-directionalfocus
problem is though it isn't aware of recent windows!
